# Generated by Django 6.0.3 on 2026-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tokenrecuperacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrecuperacao',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
