# Generated by Django 6.0.3 on 2026-06-16 19:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=40, unique=True, verbose_name='Nome da cor')),
            ],
            options={
                'verbose_name': 'Cor',
                'verbose_name_plural': 'Cores',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Nº Patrimônio')),
                ('modelo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Manutenção'), ('EMPRESTADO', 'Emprestado')], default='DISPONIVEL', max_length=15)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand')),
            ],
            options={
                'verbose_name': 'Notebook',
            },
        ),
    ]
