# Generated by Django 6.0.3 on 2026-04-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_color', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='numero_patrimonio',
            field=models.IntegerField(unique=True, verbose_name='Nº Patrimônio'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.color'),
        ),
    ]
