# Generated by Django 6.0.3 on 2026-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_color_alter_brand_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Cor'},
        ),
    ]
