# Generated by Django 6.0.3 on 2026-04-06 14:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_color_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand', validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
