# Generated by Django 6.0.3 on 2026-04-06 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_notebook_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='numero_patrimonio',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Nº Patrimônio'),
        ),
    ]
