# Generated by Django 6.0.3 on 2026-04-06 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_notebook_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='numero_patrimonio',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='Nº Patrimônio'),
        ),
    ]
