# Generated by Django 6.0.3 on 2026-06-16 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carregador', models.BooleanField(default=False)),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Retirada')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('horario', models.TimeField(auto_now_add=True, verbose_name='Hora do pedido')),
                ('emprestado', models.BooleanField(default=False)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovante/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=100)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notebooks', to='inventory.notebook')),
            ],
            options={
                'verbose_name': 'Empréstimo',
            },
        ),
    ]
