# Generated by Django 6.0.3 on 2026-03-26 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loans',
            name='horario',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Hora do pedido'),
            preserve_default=False,
        ),
    ]
