# Generated by Django 6.0.3 on 2026-04-06 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_color_alter_brand_brand_and_more'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovante/'),
        ),
        migrations.AddField(
            model_name='loans',
            name='emprestado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loans',
            name='horario',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Hora do pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loans',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.notebook'),
        ),
    ]
