# Generated by Django 6.0.3 on 2026-03-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('loans', '0002_loans_emprestado_loans_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.notebook'),
        ),
    ]
