# Generated by Django 6.0.3 on 2026-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loans_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovante/'),
        ),
    ]
